### ISSUE TITLE
Why check-in node modules folder?

### ISSUE THREAD

**Issue by meyyappanv** [nikhileshatverma/Bank_Details_fetching_API#1]
Checkng-in node modules folder is a bad practice.
The package-lock.json is more than sufficient.

See https://stackoverflow.com/questions/11459475/should-i-check-in-folder-node-modules-to-git-when-creating-a-node-js-app-on-he

Could you please remove node_modules folder?

**Comment by nikhileshatverma** [comment]
Yes sure I agree, our motive could get fulfilled by the package-lock.json file only I am removing it.
